version: '3.9'

services:
    db:
        image: mysql:8.0.25
        ports:
            - "${MYSQL_PORT}:3306"
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - symfony
        expose:
            - 3306

    php:
        build:
            context: ./docker/php-fpm
            args:
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION: 4.23.2
        ports:
            - "${PHP_PORT}:9001"
        volumes:
            - ./symfony:/var/www/symfony/     
<<<<<<< Updated upstream
            #- /var/www/symfony/vendor
            #- /var/www/symfony/var/cache  
=======
        #    - /var/www/symfony/vendor
        #    - /var/www/symfony/var/cache  
>>>>>>> Stashed changes
            - ./logs/php/:/var/log/php8    
            - ./logs/symfony:/var/www/symfony/var/log     
        labels:
          ofelia.enabled: "true"
          ofelia.job-exec.dataFetcher.schedule: "@every 30s"
          ofelia.job-exec.dataFetcher.command: "php bin/console updateData"  
        depends_on:
            - db
            - ofelia
        networks:
            - symfony

    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "${PHPMYADMIN_PORT}:80"
        depends_on:
            - php
            - db
        restart: always
        networks:
            - symfony

    nginx:
        build: 
            context: ./docker/nginx
            args:
                NGINX_SYMFONY_SERVER_NAME: ${NGINX_SYMFONY_SERVER_NAME}
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - db
        environment:
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
            - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
            - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME}
        volumes:
            - ./symfony:/var/www/symfony/
            - ./logs/nginx:/var/log/nginx
        links:
          - db
        networks:
            - symfony
    sftp:           
        image: atmoz/sftp:debian-stretch
        volumes:
            - ./FTPFolder/:/home/admin/FTPFolder
           # - ./FTPFolder/IN/:/home/admin/FTPFolder/IN
           # - ./FTPFolder/OUT/:/home/admin/FTPFolder/OUT
           # - ./FTPFolder/ERROR/:/home/admin/FTPFolder/ERROR
        ports:
            - "${FTP_PORT}:22"
        command: ${FTP_USER}:${FTP_PASSWORD}:${FTP_TIMEOUT}
        networks:
            - symfony
        expose:
            - 3306
            - 22
    ofelia:
        image: mcuadros/ofelia:latest
        depends_on:
          - nginx
        command: daemon --docker
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro


networks:
    symfony: