#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path:       /
  controller: App\Controller\IndexController::fetchFTP

fetchFtp:
  path:       /fetchFTP
  controller: App\Controller\IndexController::fetchFTP

fetchAndConsumeRemoteApi:
  path:       /fetchRemoteApi
  controller: App\Controller\IndexController::fetchApi
